{"name": "Successfully search for a product", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=58558): Max retries exceeded with url: /session/c08b68c4b8ef4a305466a60c0c1b0b56/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041856d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/opt/anaconda3/lib/python3.12/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/anaconda3/lib/python3.12/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/test_steps.py\", line 147, in step_see_search_results\n    results = WebDriverWait(context.driver, 5).until(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/selenium/webdriver/support/wait.py\", line 96, in until\n    value = method(self._driver)\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/selenium/webdriver/support/expected_conditions.py\", line 84, in _predicate\n    return driver.find_element(*locator)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 766, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py\", line 391, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py\", line 415, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/urllib3/_request_methods.py\", line 143, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/urllib3/_request_methods.py\", line 278, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/urllib3/util/retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Given I am on the homepage", "status": "passed", "start": 1739642306519, "stop": 1739642307437}, {"name": "When I enter \"Laptop\" into the search bar", "status": "passed", "start": 1739642307437, "stop": 1739642312658}, {"name": "And I click the search button", "status": "passed", "start": 1739642312658, "stop": 1739642312665}, {"name": "Then I should see results related to \"Laptop\"", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=58558): Max retries exceeded with url: /session/c08b68c4b8ef4a305466a60c0c1b0b56/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041856d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/opt/anaconda3/lib/python3.12/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/anaconda3/lib/python3.12/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/test_steps.py\", line 147, in step_see_search_results\n    results = WebDriverWait(context.driver, 5).until(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/selenium/webdriver/support/wait.py\", line 96, in until\n    value = method(self._driver)\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/selenium/webdriver/support/expected_conditions.py\", line 84, in _predicate\n    return driver.find_element(*locator)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 766, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py\", line 391, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py\", line 415, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/urllib3/_request_methods.py\", line 143, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/urllib3/_request_methods.py\", line 278, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/urllib3/util/retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1739642312665, "stop": 1739642312672}], "start": 1739642306519, "stop": 1739642312673, "uuid": "54d107ca-bb8f-41e0-a48b-3a492e8660ea", "historyId": "5ff1f649bd5f362e1870f4a01e91f935", "fullName": "Search Functionality: Successfully search for a product", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Search Functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}